(() => {
  // ---------------- PUISSANCE 4 ----------------
  const c4={board:Array(42).fill(0),turn:1,playing:false,score:0,best:Babi.getBest('connect4'),aiTimer:null};
  const c4El=()=>document.getElementById('connect4-board'); document.getElementById('connect4-highscore').textContent=c4.best;
  function c4Init(){clearTimeout(c4.aiTimer);c4.board=Array(42).fill(0);c4.turn=1;c4.playing=true;c4.score=0;document.getElementById('connect4-score').textContent='0';document.getElementById('connect4-status').textContent='À vous';c4Render()}
  function c4Render(win=[]){const el=c4El();el.innerHTML='';for(let r=0;r<6;r++)for(let c=0;c<7;c++){const b=document.createElement('button');b.className='connect4-cell';const v=c4.board[r*7+c];if(v===1)b.classList.add('red');if(v===2)b.classList.add('yellow');if(win.includes(r*7+c))b.classList.add('win');b.addEventListener('click',()=>c4Play(c));el.appendChild(b)}}
  function c4Drop(col,p){for(let r=5;r>=0;r--){const i=r*7+col;if(!c4.board[i]){c4.board[i]=p;return i}}return -1}
  function c4Winner(){const dirs=[[0,1],[1,0],[1,1],[1,-1]];for(let r=0;r<6;r++)for(let c=0;c<7;c++){const p=c4.board[r*7+c];if(!p)continue;for(const [dr,dc] of dirs){const cells=[r*7+c];for(let k=1;k<4;k++){const rr=r+dr*k,cc=c+dc*k;if(rr<0||rr>=6||cc<0||cc>=7||c4.board[rr*7+cc]!==p)break;cells.push(rr*7+cc)}if(cells.length===4)return {p,cells}}}return null}
  function c4Play(col){if(!c4.playing||c4.turn!==1)return;const i=c4Drop(col,1);if(i<0)return;c4Render();if(c4Finish())return;c4.turn=2;document.getElementById('connect4-status').textContent='IA…';c4.aiTimer=setTimeout(c4AI,450)}
  function c4Finish(){const w=c4Winner();if(w){c4.playing=false;c4Render(w.cells);if(w.p===1){c4.score+=100;document.getElementById('connect4-score').textContent=c4.score;c4.best=Babi.setBest('connect4',c4.score);document.getElementById('connect4-highscore').textContent=c4.best;Babi.win('connect4','PUISSANCE 4 !',`Victoire • Score ${c4.score}`,'🟡')}else Babi.win('connect4','Partie terminée',`L’IA gagne • Score ${c4.score}`,'🤖');return true}if(c4.board.every(Boolean)){c4.playing=false;Babi.win('connect4','Égalité',`Plateau plein • Score ${c4.score}`,'🤝');return true}return false}
  function c4AI(){if(!c4.playing)return;let options=[];for(let c=0;c<7;c++){if(c4.board[c])continue;const clone=[...c4.board];const i=c4Drop(c,2);const w=c4Winner();c4.board=clone;if(w?.p===2){options=[c];break}}
    if(!options.length){for(let c=0;c<7;c++){if(c4.board[c])continue;const clone=[...c4.board];c4Drop(c,1);const w=c4Winner();c4.board=clone;if(w?.p===1){options=[c];break}}}
    if(!options.length){for(let i=0;i<7;i++)if(!c4.board[i])options.push(i);options.sort((a,b)=>Math.abs(3-a)-Math.abs(3-b));if(options.length>1)options=options.slice(0,Math.min(3,options.length));void options[Math.floor(Math.random()*options.length)]}
    const col=options[0]??3;c4Drop(col,2);c4Render();if(c4Finish())return;c4.turn=1;document.getElementById('connect4-status').textContent='À vous'}
  document.addEventListener('start-connect4',c4Init);document.getElementById('connect4-reset').addEventListener('click',c4Init);

  // ---------------- 2048 ----------------
  const game2048={grid:Array(16).fill(0),score:0,best:Babi.getBest('2048'),playing:true, touch:null};document.getElementById('2048-highscore').textContent=game2048.best;
  function new2048(){game2048.grid=Array(16).fill(0);game2048.score=0;game2048.playing=true;document.getElementById('2048-score').textContent='0';add2048();add2048();render2048();document.getElementById('game-2048').focus()}
  function add2048(){const free=game2048.grid.map((v,i)=>v?null:i).filter(v=>v!==null);if(!free.length)return false;const i=free[Math.floor(Math.random()*free.length)];game2048.grid[i]=Math.random()<.9?2:4;return true}
  function slideLine(line){const vals=line.filter(Boolean),out=[];for(let i=0;i<vals.length;i++){if(vals[i]===vals[i+1]){const v=vals[i]*2;out.push(v);game2048.score+=v;i++}else out.push(vals[i])}while(out.length<4)out.push(0);return out}
  function move2048(dir){if(!game2048.playing)return;const old=game2048.grid.join(',');const g=game2048.grid;let n=Array(16).fill(0);const write=(line,indices)=>{const s=dir==='left'||dir==='up'?line:line.slice().reverse();const r=slideLine(s);const rr=dir==='left'||dir==='up'?r:r.slice().reverse();indices.forEach((id,i)=>n[id]=rr[i])};
    if(dir==='left'||dir==='right')for(let r=0;r<4;r++)write([0,1,2,3].map(c=>g[r*4+c]),[0,1,2,3].map(c=>r*4+c));else for(let c=0;c<4;c++)write([0,1,2,3].map(r=>g[r*4+c]),[0,1,2,3].map(r=>r*4+c));
    if(dir==='right'||dir==='down'){/* reverse handled by write */}
    game2048.grid=n;if(old===n.join(','))return;document.getElementById('2048-score').textContent=game2048.score;if(game2048.score>game2048.best){game2048.best=game2048.score;localStorage.setItem(Babi.scoreKey('2048'),String(game2048.best));document.getElementById('2048-highscore').textContent=game2048.best}Babi.vibrate(8);if(n.includes(2048)){game2048.playing=false;Babi.win('2048','2048 atteint !',`Score ${game2048.score}`,'🏆')}else if(!add2048()){game2048.playing=false;Babi.win('2048','Plus de mouvements',`Score ${game2048.score}`,'🔢')}render2048()}
  function render2048(){const el=document.getElementById('game-2048');el.innerHTML='';game2048.grid.forEach(v=>{const d=document.createElement('div');d.className=`tile-2048 ${v?'v'+v:''}`;d.textContent=v||'';el.appendChild(d)})}
  const g2048=document.getElementById('game-2048');g2048.addEventListener('keydown',e=>{const m={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}[e.key];if(m){e.preventDefault();move2048(m)}});g2048.addEventListener('touchstart',e=>{const t=e.changedTouches[0];game2048.touch={x:t.clientX,y:t.clientY}},{passive:true});g2048.addEventListener('touchend',e=>{if(!game2048.touch)return;const t=e.changedTouches[0],dx=t.clientX-game2048.touch.x,dy=t.clientY-game2048.touch.y;game2048.touch=null;if(Math.max(Math.abs(dx),Math.abs(dy))<25)return;move2048(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'))},{passive:true});document.addEventListener('start-2048',new2048);document.getElementById('2048-reset').addEventListener('click',new2048);

  // ---------------- MEMORY ----------------
  const mem={cards:[],first:null,second:null,lock:false,moves:0,score:0,best:Babi.getBest('memory')};document.getElementById('memory-highscore').textContent=mem.best;
  function memoryInit(){mem.cards=[...'🍍🍉🍋🍒🍇🥝🍑🥥🍍🍉🍋🍒🍇🥝🍑🥥'].sort(()=>Math.random()-.5).map((v,i)=>({v,i,open:false,matched:false}));mem.first=null;mem.second=null;mem.lock=false;mem.moves=0;mem.score=0;document.getElementById('memory-score').textContent='0';document.getElementById('memory-moves').textContent='0';memoryRender()}
  function memoryRender(){const el=document.getElementById('memory-board');el.innerHTML='';mem.cards.forEach(card=>{const b=document.createElement('button');b.className=`memory-card ${card.open||card.matched?'flipped':''} ${card.matched?'matched':''}`;b.innerHTML=`<span class="front">${card.v}</span><span class="back">✦</span>`;b.addEventListener('click',()=>memoryFlip(card.i));el.appendChild(b)})}
  function memoryFlip(i){if(mem.lock)return;const c=mem.cards[i];if(c.open||c.matched)return;c.open=true;if(mem.first===null){mem.first=i;memoryRender();return}mem.second=i;mem.moves++;document.getElementById('memory-moves').textContent=mem.moves;memoryRender();mem.lock=true;setTimeout(()=>{const a=mem.cards[mem.first],b=mem.cards[mem.second];if(a.v===b.v){a.matched=b.matched=true;mem.score+=Math.max(40,120-mem.moves*4);Babi.vibrate([15,25,15])}else{a.open=b.open=false}mem.first=mem.second=null;mem.lock=false;document.getElementById('memory-score').textContent=mem.score;memoryRender();if(mem.cards.every(x=>x.matched)){mem.score+=Math.max(0,300-mem.moves*6);document.getElementById('memory-score').textContent=mem.score;mem.best=Babi.setBest('memory',mem.score);document.getElementById('memory-highscore').textContent=mem.best;Babi.win('memory','Mémoire parfaite !',`${mem.moves} coups • Score ${mem.score}`,'🧠')}},520)}
  document.addEventListener('start-memory',memoryInit);document.getElementById('memory-reset').addEventListener('click',memoryInit);

  // ---------------- TETRIS ----------------
  const t={canvas:document.getElementById('tetris-canvas'),ctx:null,w:10,h:20,board:[],piece:null,x:0,y:0,score:0,best:Babi.getBest('tetris'),level:1,running:false,last:0,acc:0,raf:0};t.ctx=t.canvas.getContext('2d');document.getElementById('tetris-highscore').textContent=t.best;
  const SHAPES=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]],[[1,1,0],[0,1,1]],[[0,1,1],[1,1,0]]];
  function tResize(){const p=Math.min(86*window.innerWidth/100,520);t.canvas.style.width=`${Math.min(p,360)}px`;t.canvas.style.height=`${Math.min(p*2,640)}px`;t.canvas.width=300;t.canvas.height=600}
  function tNewPiece(){const shape=SHAPES[Math.floor(Math.random()*SHAPES.length)].map(r=>r.slice());t.piece=shape;t.x=Math.floor((t.w-shape[0].length)/2);t.y=0;if(tCollides(t.x,t.y,t.piece)){t.running=false;t.best=Babi.setBest('tetris',t.score);document.getElementById('tetris-highscore').textContent=t.best;Babi.win('tetris','GAME OVER',`Score ${t.score} • Niveau ${t.level}`,'🧱')}}
  function tCollides(x,y,shape){for(let r=0;r<shape.length;r++)for(let c=0;c<shape[r].length;c++)if(shape[r][c]){const xx=x+c,yy=y+r;if(xx<0||xx>=t.w||yy>=t.h||(yy>=0&&t.board[yy][xx]))return true}return false}
  function tMerge(){for(let r=0;r<t.piece.length;r++)for(let c=0;c<t.piece[r].length;c++)if(t.piece[r][c]&&t.y+r>=0)t.board[t.y+r][t.x+c]=1}
  function tClear(){let lines=0;for(let r=t.h-1;r>=0;r--){if(t.board[r].every(Boolean)){t.board.splice(r,1);t.board.unshift(Array(t.w).fill(0));lines++;r++}}if(lines){t.score+=[0,100,300,500,800][lines]*t.level;t.level=1+Math.floor(t.score/1000);document.getElementById('tetris-score').textContent=t.score;document.getElementById('tetris-level').textContent=t.level;if(t.score>t.best){t.best=t.score;localStorage.setItem(Babi.scoreKey('tetris'),String(t.best));document.getElementById('tetris-highscore').textContent=t.best}Babi.wow()}}
  function tRotate(){const s=t.piece,r=s.map((_,i)=>s.map(row=>row[i]).reverse());if(!tCollides(t.x,t.y,r))t.piece=r}
  function tDrop(){if(!t.running)return;if(!tCollides(t.x,t.y+1,t.piece)){t.y++;return}tMerge();tClear();tNewPiece()}
  function tDraw(){const ctx=t.ctx;ctx.clearRect(0,0,300,600);ctx.fillStyle='rgba(6,10,20,.96)';ctx.fillRect(0,0,300,600);const cw=30,ch=30;for(let r=0;r<t.h;r++)for(let c=0;c<t.w;c++)if(t.board[r][c]){ctx.fillStyle='#35e8ff';ctx.fillRect(c*cw+2,r*ch+2,cw-4,ch-4)}if(t.piece)for(let r=0;r<t.piece.length;r++)for(let c=0;c<t.piece[r].length;c++)if(t.piece[r][c]){ctx.fillStyle='#a56dff';ctx.fillRect((t.x+c)*cw+2,(t.y+r)*ch+2,cw-4,ch-4)}}
  function tLoop(now){if(!t.running)return;const dt=now-t.last;t.last=now;t.acc+=dt;const delay=Math.max(95,700-(t.level-1)*55);while(t.acc>=delay){t.acc-=delay;tDrop();if(!t.running)return}tDraw();t.raf=requestAnimationFrame(tLoop)}
  function tInit(){cancelAnimationFrame(t.raf);tResize();t.board=Array.from({length:t.h},()=>Array(t.w).fill(0));t.score=0;t.level=1;t.running=true;t.piece=null;document.getElementById('tetris-score').textContent='0';document.getElementById('tetris-level').textContent='1';tNewPiece();t.last=performance.now();t.acc=0;tDraw();t.raf=requestAnimationFrame(tLoop)}
  document.addEventListener('keydown',e=>{if(!t.running)return;if(e.key==='ArrowLeft'&&!tCollides(t.x-1,t.y,t.piece)){t.x--;e.preventDefault()}else if(e.key==='ArrowRight'&&!tCollides(t.x+1,t.y,t.piece)){t.x++;e.preventDefault()}else if(e.key==='ArrowDown'){tDrop();e.preventDefault()}else if(e.key==='ArrowUp'){tRotate();e.preventDefault()}else if(e.code==='Space'){while(!tCollides(t.x,t.y+1,t.piece))t.y++;tDrop();e.preventDefault()}});window.addEventListener('resize',()=>t.running&&tResize());document.addEventListener('start-tetris',tInit);document.addEventListener('stop-tetris',()=>{t.running=false;cancelAnimationFrame(t.raf)});document.getElementById('tetris-reset').addEventListener('click',tInit);
})();
