(() => {
  const $ = id => document.getElementById(id);

  // ========================= PUISSANCE 4 =========================
  const c4 = { board: [], playing:false, aiTimer:0, score:0, best:Babi.getBest('connect4'), lastMove:-1 };
  const C4_ROWS=6, C4_COLS=7;
  $('connect4-highscore').textContent=String(c4.best);
  function c4Init(){clearTimeout(c4.aiTimer);c4.board=Array(C4_ROWS*C4_COLS).fill(0);c4.playing=true;c4.score=0;c4.lastMove=-1;$('connect4-score').textContent='0';$('connect4-highscore').textContent=String(c4.best);$('connect4-status').textContent='À vous';c4Render();}
  function c4Drop(col,player){for(let r=C4_ROWS-1;r>=0;r--){const i=r*C4_COLS+col;if(!c4.board[i]){c4.board[i]=player;c4.lastMove=i;return i;}}return -1;}
  function c4Winner(){
    const b=c4.board;
    const dirs=[[0,1],[1,0],[1,1],[1,-1]];
    for(let r=0;r<C4_ROWS;r++)for(let c=0;c<C4_COLS;c++){const p=b[r*7+c];if(!p)continue;for(const [dr,dc] of dirs){const cells=[];for(let k=0;k<4;k++){const rr=r+dr*k,cc=c+dc*k;if(rr<0||rr>=6||cc<0||cc>=7||b[rr*7+cc]!==p)break;cells.push(rr*7+cc);}if(cells.length===4)return {p,cells};}}
    return b.includes(0)?null:{p:0,cells:[]};
  }
  function c4Render(winCells=[]){
    const grid=$('connect4-board');if(!grid)return;grid.innerHTML='';const winSet=new Set(winCells);
    for(let i=0;i<42;i++){const cell=document.createElement('button');cell.type='button';cell.className='connect4-cell';cell.setAttribute('aria-label',`Colonne ${i%7+1}, ligne ${Math.floor(i/7)+1}`);if(c4.board[i]){cell.classList.add(c4.board[i]===1?'red':'yellow');cell.setAttribute('aria-label',`${c4.board[i]===1?'Rouge':'Jaune'} — colonne ${i%7+1}`);}if(i===c4.lastMove)cell.classList.add('drop-in');if(winSet.has(i))cell.classList.add('win');cell.addEventListener('click',()=>c4Human(i%7));grid.appendChild(cell);}
  }
  function c4Human(col){if(!c4.playing||c4.board[col]||c4.aiTimer)return;if(c4Drop(col,1)<0)return;Babi.vibrate(12);c4.score+=25;$('connect4-score').textContent=String(c4.score);c4Render();if(c4Finish())return;c4.playing=true;$('connect4-status').textContent='🤖 Réflexion…';c4.aiTimer=setTimeout(c4AI,480);}
  function c4Finish(){const w=c4Winner();if(!w)return false;c4.playing=false;clearTimeout(c4.aiTimer);c4.aiTimer=0;c4Render(w.cells);if(w.p===1){c4.score+=500;c4.best=Babi.setBest('connect4',c4.score);$('connect4-highscore').textContent=String(c4.best);$('connect4-score').textContent=String(c4.score);$('connect4-status').textContent='Victoire !';Babi.vibrate([80,40,100]);Babi.win('connect4','Victoire !',`Vous battez l’IA • Score ${c4.score}`,'🎯');}else if(w.p===2){$('connect4-status').textContent='Défaite';Babi.vibrate(120);Babi.win('connect4','Partie terminée',`L’IA gagne • Score ${c4.score} • Meilleur ${c4.best}`,'🤖');}else{$('connect4-status').textContent='Égalité';Babi.win('connect4','Égalité',`Score ${c4.score} • Meilleur ${c4.best}`,'🤝');}return true;}
  function c4CanWin(col,player){if(c4.board[col])return false;const clone=c4.board.slice();const i=c4Drop(col,player);const win=c4Winner()?.p===player;c4.board=clone;c4.lastMove=-1;return win;}
  function c4AI(){c4.aiTimer=0;if(!c4.playing)return;let choices=[];for(let c=0;c<7;c++)if(c4CanWin(c,2)){choices=[c];break;}if(!choices.length)for(let c=0;c<7;c++)if(c4CanWin(c,1)){choices=[c];break;}if(!choices.length){choices=[0,1,2,3,4,5,6].filter(c=>!c4.board[c]);choices.sort((a,b)=>Math.abs(3-a)-Math.abs(3-b));choices=choices.slice(0,3);}const col=choices[Math.floor(Math.random()*choices.length)];if(c4Drop(col,2)<0)return;c4Render();Babi.vibrate(10);if(!c4Finish()){c4.playing=true;$('connect4-status').textContent='À vous';}}
  document.addEventListener('start-connect4',c4Init);document.addEventListener('stop-connect4',()=>{clearTimeout(c4.aiTimer);c4.aiTimer=0;c4.playing=false;});$('connect4-reset')?.addEventListener('click',c4Init);

  // ========================= 2048 =========================
  let board2048=[],score2048=0,playing2048=false,reached2048=false;
  const best2048=Babi.getBest('2048');$('2048-highscore').textContent=String(best2048);
  function init2048(){board2048=Array(16).fill(0);score2048=0;playing2048=true;reached2048=false;$('2048-score').textContent='0';$('2048-highscore').textContent=String(Babi.getBest('2048'));$('2048-status').textContent='Flèches, swipe ou boutons • fusionnez les tuiles identiques.';spawn2048();spawn2048();render2048();$('game-2048')?.focus({preventScroll:true});}
  function spawn2048(){const empty=board2048.map((v,i)=>v===0?i:-1).filter(i=>i>=0);if(!empty.length)return;const i=empty[Math.floor(Math.random()*empty.length)];board2048[i]=Math.random()<.9?2:4;}
  function render2048(){const grid=$('game-2048');if(!grid)return;grid.innerHTML='';for(const val of board2048){const cell=document.createElement('div');cell.className=`tile-2048 ${val?`v${val}`:''} ${val>=1024?'compact-value':''}`;cell.textContent=val||'';grid.appendChild(cell);}}
  function move2048(dir){
    if(!playing2048)return;const old=board2048.slice();let moved=false, gained=0;const line=[];
    const slide=row=>{const arr=row.filter(Boolean),out=[];for(let i=0;i<arr.length;i++){if(arr[i]===arr[i+1]){const v=arr[i]*2;out.push(v);gained+=v;i++;}else out.push(arr[i]);}while(out.length<4)out.push(0);return out;};
    for(let i=0;i<4;i++){const row=[];for(let j=0;j<4;j++){const k=dir==='LEFT'||dir==='RIGHT'?i*4+j:j*4+i;row.push(board2048[k]);}if(dir==='RIGHT'||dir==='DOWN')row.reverse();const result=slide(row);if(dir==='RIGHT'||dir==='DOWN')result.reverse();for(let j=0;j<4;j++){const k=dir==='LEFT'||dir==='RIGHT'?i*4+j:j*4+i;if(board2048[k]!==result[j])moved=true;line.push([k,result[j]]);}}
    if(!moved)return Babi.toast('↔️ Aucun mouvement possible');
    board2048=Array(16).fill(0);line.forEach(([k,v])=>board2048[k]=v);score2048+=gained;$('2048-score').textContent=String(score2048);const best=Babi.setBest('2048',score2048);$('2048-highscore').textContent=String(best);spawn2048();render2048();Babi.vibrate(gained?18:8);
    if(board2048.includes(2048)&&!reached2048){reached2048=true;playing2048=false;Babi.win('2048','2048 atteint !',`Score ${score2048} • Meilleur ${best}`,'🏆');return;}
    if(!canMove2048()){playing2048=false;Babi.win('2048','Game Over',`Score ${score2048} • Meilleur ${best}`,'🧩');}
  }
  function canMove2048(){if(board2048.includes(0))return true;for(let r=0;r<4;r++)for(let c=0;c<4;c++){const i=r*4+c;if(c<3&&board2048[i]===board2048[i+1])return true;if(r<3&&board2048[i]===board2048[i+4])return true;}return false;}
  document.addEventListener('start-2048',init2048);document.addEventListener('stop-2048',()=>{playing2048=false;});$('2048-reset')?.addEventListener('click',init2048);
  document.addEventListener('keydown',e=>{if(!playing2048)return;const map={ArrowUp:'UP',ArrowDown:'DOWN',ArrowLeft:'LEFT',ArrowRight:'RIGHT'};if(map[e.key]){e.preventDefault();move2048(map[e.key]);}});
  let touch2048=null;const grid2048=$('game-2048');grid2048?.addEventListener('touchstart',e=>{const t=e.changedTouches[0];touch2048={x:t.clientX,y:t.clientY};},{passive:true});grid2048?.addEventListener('touchend',e=>{if(!touch2048)return;const t=e.changedTouches[0],dx=t.clientX-touch2048.x,dy=t.clientY-touch2048.y;touch2048=null;if(Math.max(Math.abs(dx),Math.abs(dy))<24)return;if(Math.abs(dx)>Math.abs(dy))move2048(dx>0?'RIGHT':'LEFT');else move2048(dy>0?'DOWN':'UP');},{passive:true});
  document.querySelectorAll('[data-2048-dir]').forEach(btn=>btn.addEventListener('pointerdown',()=>move2048(btn.dataset['2048Dir'])));

  // ========================= MEMORY =========================
  const memIcons=['🍎','🍌','🍇','🍉','🍓','🍒','🍍','🥝'];let memCards=[],memFlipped=[],memMatched=0,memLock=false,memMoves=0,memTimer=0,memPlaying=false;let memBest=Babi.getBest('memory');$('memory-highscore').textContent=String(memBest);
  function initMemory(){clearTimeout(memTimer);const grid=$('memory-board');if(!grid)return;memPlaying=true;memLock=false;memFlipped=[];memMatched=0;memMoves=0;$('memory-score').textContent='0';$('memory-moves').textContent='0';$('memory-highscore').textContent=String(memBest);$('memory-status').textContent='Retournez deux cartes. Moins de coups = meilleur score.';memCards=[...memIcons,...memIcons].sort(()=>Math.random()-.5);grid.innerHTML='';memCards.forEach((icon,i)=>{const card=document.createElement('button');card.type='button';card.className='memory-card';card.dataset.icon=icon;card.dataset.index=i;card.setAttribute('aria-label','Carte cachée');card.innerHTML='<span class="front" aria-hidden="true"></span><span class="back" aria-hidden="true">?</span>';card.addEventListener('click',()=>flipMemory(card));grid.appendChild(card);});}
  function flipMemory(card){if(!memPlaying||memLock||card.classList.contains('flipped')||card.classList.contains('matched'))return;const front=card.querySelector('.front');front.textContent=card.dataset.icon;card.classList.add('flipped');card.setAttribute('aria-label',`Carte ${card.dataset.icon}`);memFlipped.push(card);Babi.vibrate(8);if(memFlipped.length!==2)return;memMoves++;$('memory-moves').textContent=String(memMoves);memLock=true;const [a,b]=memFlipped;if(a.dataset.icon===b.dataset.icon){a.classList.add('matched');b.classList.add('matched');memMatched+=2;memFlipped=[];memLock=false;const liveScore=Math.max(0,10000-memMoves*250);$('memory-score').textContent=String(liveScore);if(memMatched===memCards.length){memPlaying=false;const finalScore=Math.max(100,10000-memMoves*250);memBest=Babi.setBest('memory',finalScore);$('memory-highscore').textContent=String(memBest);$('memory-score').textContent=String(finalScore);$('memory-status').textContent=`🎉 Terminé en ${memMoves} coups`;Babi.vibrate([50,50,100]);Babi.win('memory','Mémoire parfaite !',`Terminé en ${memMoves} coups • Score ${finalScore}`,'🧠');}}else{memTimer=setTimeout(()=>{if(!memPlaying&&memMatched===memCards.length)return;a.classList.remove('flipped');b.classList.remove('flipped');a.querySelector('.front').textContent='';b.querySelector('.front').textContent='';a.setAttribute('aria-label','Carte cachée');b.setAttribute('aria-label','Carte cachée');memFlipped=[];memLock=false;},760);}}
  document.addEventListener('start-memory',initMemory);document.addEventListener('stop-memory',()=>{memPlaying=false;clearTimeout(memTimer);});$('memory-reset')?.addEventListener('click',initMemory);

  // ========================= TETRIS =========================
  const tCanvas=$('tetris-canvas'),tCtx=tCanvas?.getContext('2d');if(tCanvas&&tCtx){
    const ROWS=20,COLS=10,BASE=28;let tBoard=[],tPiece=null,tScore=0,tLevel=1,tLines=0,tDrop=0,tLast=0,tRaf=0,tPlaying=false,tPaused=false;
    const pieces=[
      {m:[[1,1,1,1]],c:'#2de2e6'},{m:[[1,1],[1,1]],c:'#ffe45c'},{m:[[0,1,0],[1,1,1]],c:'#b76cff'},
      {m:[[1,0,0],[1,1,1]],c:'#4f7cff'},{m:[[0,0,1],[1,1,1]],c:'#ff9e4f'},{m:[[0,1,1],[1,1,0]],c:'#45ef9b'},{m:[[1,1,0],[0,1,1]],c:'#ff5577'}
    ];
    function sizeCanvas(){const css=Math.max(230,Math.min(innerWidth*.86,520,innerHeight*.88/2));const dpr=Math.min(devicePixelRatio||1,2);tCanvas.style.width=`${css}px`;tCanvas.style.height=`${Math.round(css*2)}px`;tCanvas.width=COLS*BASE*dpr;tCanvas.height=ROWS*BASE*dpr;tCtx.setTransform(dpr,0,0,dpr,0,0);drawTetris();}
    const copyMatrix=m=>m.map(r=>r.slice());
    function resetTetris(){cancelAnimationFrame(tRaf);tBoard=Array.from({length:ROWS},()=>Array(COLS).fill(0));tPiece=null;tScore=0;tLines=0;tLevel=1;tDrop=0;tPaused=false;tPlaying=true;$('tetris-score').textContent='0';$('tetris-level').textContent='1';$('tetris-highscore').textContent=String(Babi.getBest('tetris'));$('tetris-status').textContent='← → déplacer • ↻ tourner • ↓ accélérer • Chute = descente instantanée';sizeCanvas();spawnTetris();tLast=performance.now();tRaf=requestAnimationFrame(updateTetris);}
    function spawnTetris(){const src=pieces[Math.floor(Math.random()*pieces.length)];tPiece={matrix:copyMatrix(src.m),color:src.c,x:Math.floor(COLS/2)-Math.ceil(src.m[0].length/2),y:0};if(collide(tPiece)){tPlaying=false;const best=Babi.setBest('tetris',tScore);$('tetris-highscore').textContent=String(best);Babi.win('tetris','Game Over',`Score ${tScore} • Meilleur ${best}`,'🧱');}}
    function syncTetrisScore(){ $('tetris-score').textContent=String(tScore); const best=Babi.setBest('tetris',tScore); $('tetris-highscore').textContent=String(best); }
    function collide(piece){for(let y=0;y<piece.matrix.length;y++)for(let x=0;x<piece.matrix[y].length;x++)if(piece.matrix[y][x]){const bx=piece.x+x,by=piece.y+y;if(bx<0||bx>=COLS||by>=ROWS)return true;if(by>=0&&tBoard[by][bx])return true;}return false;}
    function merge(){for(let y=0;y<tPiece.matrix.length;y++)for(let x=0;x<tPiece.matrix[y].length;x++)if(tPiece.matrix[y][x]&&tPiece.y+y>=0)tBoard[tPiece.y+y][tPiece.x+x]=tPiece.color;}
    function clearLines(){let n=0;for(let y=ROWS-1;y>=0;y--){if(tBoard[y].every(Boolean)){tBoard.splice(y,1);tBoard.unshift(Array(COLS).fill(0));n++;y++;}}if(!n)return;const scores=[0,100,300,500,800];tScore+=scores[n]*tLevel;tLines+=n;tLevel=Math.floor(tLines/10)+1;$('tetris-score').textContent=String(tScore);$('tetris-level').textContent=String(tLevel);const best=Babi.setBest('tetris',tScore);$('tetris-highscore').textContent=String(best);$('tetris-status').textContent=`✨ ${n} ligne${n>1?'s':''} effacée${n>1?'s':''} • Niveau ${tLevel}`;Babi.vibrate(30*n);}
    function move(dx){if(!tPlaying||tPaused)return;tPiece.x+=dx;if(collide(tPiece))tPiece.x-=dx;drawTetris();}
    function softDrop(){if(!tPlaying||tPaused)return;if(!moveDown())tDrop=0;}
    function moveDown(){tPiece.y++;if(collide(tPiece)){tPiece.y--;merge();clearLines();spawnTetris();return false;}tScore+=1;syncTetrisScore();return true;}
    function hardDrop(){if(!tPlaying||tPaused)return;let dist=0;while(true){tPiece.y++;if(collide(tPiece)){tPiece.y--;break;}dist++;}tScore+=dist*2;syncTetrisScore();merge();clearLines();Babi.vibrate(18);spawnTetris();drawTetris();}
    function rotate(){if(!tPlaying||tPaused)return;const old=copyMatrix(tPiece.matrix);tPiece.matrix=tPiece.matrix[0].map((_,i)=>tPiece.matrix.map(row=>row[i]).reverse());let kicks=0;if(collide(tPiece)){for(const k of [-1,1,-2,2]){tPiece.x+=k;if(!collide(tPiece)){kicks=k;break;}tPiece.x-=k;}}if(kicks===0&&collide(tPiece))tPiece.matrix=old;drawTetris();Babi.vibrate(8);}
    function ghostY(){let y=tPiece.y;while(true){const test={...tPiece,y:y+1};if(collide(test))return y;y++;}}
    function drawBlock(x,y,size,color,ghost=false){tCtx.fillStyle=ghost?'rgba(255,255,255,.10)':color;tCtx.fillRect(x*BASE+1,y*BASE+1,BASE-2,BASE-2);if(!ghost){const g=tCtx.createLinearGradient(x*BASE,y*BASE,(x+1)*BASE,(y+1)*BASE);g.addColorStop(0,'rgba(255,255,255,.32)');g.addColorStop(.28,'rgba(255,255,255,.02)');g.addColorStop(1,'rgba(0,0,0,.18)');tCtx.fillStyle=g;tCtx.fillRect(x*BASE+1,y*BASE+1,BASE-2,BASE-2);}}
    function drawTetris(){if(!tCtx)return;const w=COLS*BASE,h=ROWS*BASE;tCtx.clearRect(0,0,w,h);const bg=tCtx.createLinearGradient(0,0,w,h);bg.addColorStop(0,'#091224');bg.addColorStop(1,'#050811');tCtx.fillStyle=bg;tCtx.fillRect(0,0,w,h);tCtx.strokeStyle='rgba(255,255,255,.045)';for(let x=1;x<COLS;x++){tCtx.beginPath();tCtx.moveTo(x*BASE,0);tCtx.lineTo(x*BASE,h);tCtx.stroke();}for(let y=1;y<ROWS;y++){tCtx.beginPath();tCtx.moveTo(0,y*BASE);tCtx.lineTo(w,y*BASE);tCtx.stroke();}tBoard.forEach((row,y)=>row.forEach((v,x)=>v&&drawBlock(x,y,BASE,v)));if(tPiece){const gy=ghostY();tPiece.matrix.forEach((row,y)=>row.forEach((v,x)=>v&&drawBlock(tPiece.x+x,gy+y,BASE,tPiece.color,true)));tPiece.matrix.forEach((row,y)=>row.forEach((v,x)=>v&&drawBlock(tPiece.x+x,tPiece.y+y,BASE,tPiece.color)));}if(tPaused){tCtx.fillStyle='rgba(4,7,14,.7)';tCtx.fillRect(0,0,w,h);tCtx.fillStyle='#fff';tCtx.font='900 28px system-ui';tCtx.textAlign='center';tCtx.fillText('PAUSE',w/2,h/2);}}
    function togglePause(){if(!tPlaying)return;tPaused=!tPaused;$('tetris-status').textContent=tPaused?'⏸️ Pause — ↻ pour reprendre.':'← → déplacer • ↻ tourner • ↓ accélérer • Chute = descente instantanée';if(!tPaused)tLast=performance.now();drawTetris();}
    function updateTetris(now){if(!tPlaying)return;if(tPaused){tRaf=requestAnimationFrame(updateTetris);return;}const dt=now-tLast;tLast=now;tDrop+=dt;const interval=Math.max(90,800-(tLevel-1)*65);if(tDrop>interval){moveDown();tDrop=0;}drawTetris();tRaf=requestAnimationFrame(updateTetris);}
    document.addEventListener('start-tetris',resetTetris);document.addEventListener('stop-tetris',()=>{tPlaying=false;cancelAnimationFrame(tRaf);});$('tetris-reset')?.addEventListener('click',resetTetris);window.addEventListener('resize',sizeCanvas,{passive:true});
    document.addEventListener('keydown',e=>{if(!tPlaying)return;if(e.key==='ArrowLeft'){e.preventDefault();move(-1);}else if(e.key==='ArrowRight'){e.preventDefault();move(1);}else if(e.key==='ArrowDown'){e.preventDefault();softDrop();}else if(e.key==='ArrowUp'){e.preventDefault();rotate();}else if(e.code==='Space'){e.preventDefault();hardDrop();}else if(e.key.toLowerCase()==='p'){e.preventDefault();togglePause();}});
    document.querySelectorAll('[data-tetris-action]').forEach(btn=>btn.addEventListener('pointerdown',e=>{e.preventDefault();const a=btn.dataset.tetrisAction;if(a==='left')move(-1);else if(a==='right')move(1);else if(a==='rotate'){if(tPaused)togglePause();else rotate();}else if(a==='drop')hardDrop();}));
    sizeCanvas();
  }
})();
