(() => {
  const LEVELS={easy:{label:'Facile',seconds:22,chessDepth:1,checkersDepth:1,aiDelay:450},medium:{label:'Moyen',seconds:16,chessDepth:2,checkersDepth:3,aiDelay:620},hard:{label:'Expert',seconds:11,chessDepth:3,checkersDepth:4,aiDelay:820}};
  const CHESS_SYMBOL={w:{k:'♔',q:'♕',r:'♖',b:'♗',n:'♘',p:'♙'},b:{k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'}};
  const PIECE_VALUES={p:100,n:320,b:330,r:500,q:900,k:20000};
  const DIR4=[[1,1],[1,-1],[-1,1],[-1,-1]];
  let chess={level:'medium',state:null,selected:null,gameOver:false,timer:null,timeLeft:0,aiTimer:null,score:0,best:Babi.getBest('chess')};
  let checkers={level:'medium',state:null,selected:null,mustContinue:null,gameOver:false,timer:null,timeLeft:0,aiTimer:null,score:0,best:Babi.getBest('checkers')};
  document.getElementById('chess-highscore').textContent=chess.best; document.getElementById('checkers-highscore').textContent=checkers.best;

  const idx=(r,c)=>r*8+c; const rc=i=>[Math.floor(i/8),i%8]; const inside=(r,c)=>r>=0&&r<8&&c>=0&&c<8;
  function cloneChess(s){return {board:s.board.map(p=>p?{...p}:null),turn:s.turn,ep:s.ep?{...s.ep}:null,castling:{...s.castling}}}
  function initialChess(){
    const b=Array(64).fill(null); const back=['r','n','b','q','k','b','n','r'];
    for(let c=0;c<8;c++){b[idx(0,c)]={color:'b',type:back[c],moved:false};b[idx(1,c)]={color:'b',type:'p',moved:false};b[idx(6,c)]={color:'w',type:'p',moved:false};b[idx(7,c)]={color:'w',type:back[c],moved:false}}
    return {board:b,turn:'w',ep:null,castling:{wK:true,wQ:true,bK:true,bQ:true}};
  }
  function pseudoChessMoves(s,from,attacksOnly=false){
    const p=s.board[from]; if(!p)return[]; const [r,c]=rc(from),moves=[];
    const add=(rr,cc,o={})=>{if(inside(rr,cc))moves.push({from,to:idx(rr,cc),...o})};
    if(p.type==='p'){
      const d=p.color==='w'?-1:1,start=p.color==='w'?6:1;
      if(attacksOnly){for(const dc of [-1,1])if(inside(r+d,c+dc))add(r+d,c+dc,{attack:true});return moves}
      if(inside(r+d,c)&&!s.board[idx(r+d,c)]){add(r+d,c);if(r===start&&!s.board[idx(r+2*d,c)])add(r+2*d,c,{double:true})}
      for(const dc of [-1,1]){const t=inside(r+d,c+dc)?s.board[idx(r+d,c+dc)]:null;if(t&&t.color!==p.color)add(r+d,c+dc,{capture:true});else if(s.ep&&s.ep.r===r+d&&s.ep.c===c+dc)add(r+d,c+dc,{enPassant:true,capture:true})}
    } else if(p.type==='n'){
      for(const [dr,dc] of [[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]]){if(!inside(r+dr,c+dc))continue;const t=s.board[idx(r+dr,c+dc)];if(attacksOnly||!t||t.color!==p.color)add(r+dr,c+dc,{capture:!!t})}
    } else if(['b','r','q'].includes(p.type)){
      const dirs=p.type==='b'?DIR4:p.type==='r'?[[1,0],[-1,0],[0,1],[0,-1]]:[...DIR4,[1,0],[-1,0],[0,1],[0,-1]];
      for(const [dr,dc] of dirs){for(let n=1;n<8;n++){const rr=r+dr*n,cc=c+dc*n;if(!inside(rr,cc))break;const t=s.board[idx(rr,cc)];if(attacksOnly){moves.push({from,to:idx(rr,cc),attack:true});if(t)break;continue}if(!t){add(rr,cc)}else{if(t.color!==p.color)add(rr,cc,{capture:true});break}}}
    } else if(p.type==='k'){
      for(const [dr,dc] of [...DIR4,[1,0],[-1,0],[0,1],[0,-1]]){const rr=r+dr,cc=c+dc;if(!inside(rr,cc))continue;const t=s.board[idx(rr,cc)];if(attacksOnly||!t||t.color!==p.color)add(rr,cc,{capture:!!t})}
      if(!attacksOnly&&!p.moved&&!isSquareAttacked(s,from,p.color==='w'?'b':'w')){
        const enemy=p.color==='w'?'b':'w';
        if(s.castling[`${p.color}K`]&&!s.board[idx(r,5)]&&!s.board[idx(r,6)]&&!isSquareAttacked(s,idx(r,5),enemy)&&!isSquareAttacked(s,idx(r,6),enemy))add(r,6,{castle:'K'});
        if(s.castling[`${p.color}Q`]&&!s.board[idx(r,1)]&&!s.board[idx(r,2)]&&!s.board[idx(r,3)]&&!isSquareAttacked(s,idx(r,3),enemy)&&!isSquareAttacked(s,idx(r,2),enemy))add(r,2,{castle:'Q'});
      }
    }
    return moves;
  }
  function isSquareAttacked(s,sq,byColor){for(let i=0;i<64;i++){const p=s.board[i];if(p&&p.color===byColor){if(pseudoChessMoves(s,i,true).some(m=>m.to===sq))return true}}return false}
  function findKing(s,color){return s.board.findIndex(p=>p&&p.color===color&&p.type==='k')}
  function chessApply(s,m){
    const n=cloneChess(s),p={...n.board[m.from]}; n.board[m.from]=null; n.ep=null;
    if(m.enPassant){const [r,c]=rc(m.to);const cap=idx(p.color==='w'?r+1:r-1,c);n.board[cap]=null}
    if(m.castle){const [r,c]=rc(m.to);const rookFrom=m.castle==='K'?idx(r,7):idx(r,0),rookTo=m.castle==='K'?idx(r,5):idx(r,3);n.board[rookTo]={...n.board[rookFrom],moved:true};n.board[rookFrom]=null}
    if(p.type==='p'&&Math.abs(m.to-m.from)===16){const [r,c]=rc(m.to);n.ep={r:(rc(m.from)[0]+r)/2,c}}
    if(p.type==='p'&&rc(m.to)[0]=== (p.color==='w'?0:7))p.type='q';
    p.moved=true;n.board[m.to]=p;
    const home=p.color==='w'?7:0; if(p.type==='k'){n.castling[`${p.color}K`]=false;n.castling[`${p.color}Q`]=false} if(p.type==='r'){if(m.from===idx(home,0))n.castling[`${p.color}Q`]=false;if(m.from===idx(home,7))n.castling[`${p.color}K`]=false}
    const other=p.color==='w'?'b':'w'; if(m.to===idx(other==='w'?7:0,0))n.castling[`${other}Q`]=false;if(m.to===idx(other==='w'?7:0,7))n.castling[`${other}K`]=false;
    n.turn=other; return n;
  }
  function legalChessMoves(s,color=s.turn){const out=[];for(let i=0;i<64;i++){if(!s.board[i]||s.board[i].color!==color)continue;for(const m of pseudoChessMoves(s,i)){const n=chessApply(s,m);const k=findKing(n,color);if(k>=0&&!isSquareAttacked(n,k,color==='w'?'b':'w'))out.push(m)}}return out}
  function chessEndCheck(s,side){const moves=legalChessMoves(s,side); if(moves.length)return null;const king=findKing(s,side);if(king>=0&&isSquareAttacked(s,king,side==='w'?'b':'w'))return 'checkmate';return 'stalemate'}
  function chessEval(s){let v=0;for(const p of s.board)if(p)v+=(p.color==='b'?1:-1)*PIECE_VALUES[p.type];const bk=findKing(s,'b'),wk=findKing(s,'w');if(bk>=0&&isSquareAttacked(s,bk,'w'))v-=35;if(wk>=0&&isSquareAttacked(s,wk,'b'))v+=35;return v}
  function chessSearch(s,depth,alpha=-Infinity,beta=Infinity){if(depth===0)return chessEval(s);const moves=legalChessMoves(s,s.turn);const end=chessEndCheck(s,s.turn);if(end)return end==='checkmate'?(s.turn==='b'?-999999:999999):0;const maximizing=s.turn==='b';let best=maximizing?-Infinity:Infinity;for(const m of moves){const val=chessSearch(chessApply(s,m),depth-1,alpha,beta);if(maximizing){best=Math.max(best,val);alpha=Math.max(alpha,best)}else{best=Math.min(best,val);beta=Math.min(beta,best)}if(beta<=alpha)break}return best}
  function bestChessMove(s,depth){const moves=legalChessMoves(s,'b');if(!moves.length)return null;if(depth===1){const captures=moves.filter(m=>m.capture||m.enPassant);return (captures.length?captures:moves)[Math.floor(Math.random()*(captures.length?captures.length:moves.length))]}let best=-Infinity,chosen=moves[0];for(const m of moves){const val=chessSearch(chessApply(s,m),depth-1,-Infinity,Infinity);if(val>best){best=val;chosen=m}}return chosen}
  function chessRender(){const board=document.getElementById('chess-board');board.innerHTML='';const legal=chess.selected!==null?legalChessMoves(chess.state,'w').filter(m=>m.from===chess.selected):[];const legalMap=new Map(legal.map(m=>[m.to,m]));for(let i=0;i<64;i++){const sq=document.createElement('button');const [r,c]=rc(i);sq.className=`square ${(r+c)%2?'dark':'light'}`;if(i===chess.selected)sq.classList.add('selected');if(legalMap.has(i))sq.classList.add(legalMap.get(i).capture||legalMap.get(i).enPassant?'capture':'legal');const p=chess.state.board[i];if(p){const piece=document.createElement('span');piece.className=`piece ${p.color==='w'?'white-piece':'black-piece'}`;piece.textContent=CHESS_SYMBOL[p.color][p.type];sq.appendChild(piece)}sq.addEventListener('click',()=>chessClick(i));board.appendChild(sq)}}
  function chessClick(i){if(chess.gameOver||chess.state.turn!=='w')return;const p=chess.state.board[i];if(chess.selected===null){if(p?.color==='w'){chess.selected=i;chessRender();Babi.vibrate(18)}return}if(i===chess.selected){chess.selected=null;chessRender();return}const m=legalChessMoves(chess.state,'w').find(x=>x.from===chess.selected&&x.to===i);if(m){makeChessHuman(m)}else if(p?.color==='w'){chess.selected=i;chessRender()}else{Babi.toast('Déplacement illégal')}}
  function updateScore(game,add){game.score=Math.max(0,game.score+add);const id=game===chess?'chess':'checkers';document.getElementById(`${id}-score`).textContent=game.score;if(game.score>game.best){game.best=game.score;localStorage.setItem(Babi.scoreKey(id),String(game.best));document.getElementById(`${id}-highscore`).textContent=game.best}}
  function resetChessScore(){chess.score=0;document.getElementById('chess-score').textContent='0';document.getElementById('chess-highscore').textContent=chess.best}
  function chessHumanTimer(){clearInterval(chess.timer);chess.timeLeft=LEVELS[chess.level].seconds;document.getElementById('chess-timer').textContent=chess.timeLeft;chess.timer=setInterval(()=>{if(chess.gameOver||chess.state?.turn!=='w'){clearInterval(chess.timer);return}chess.timeLeft--;document.getElementById('chess-timer').textContent=chess.timeLeft;if(chess.timeLeft<=0){clearInterval(chess.timer);chess.status='Temps écoulé';document.getElementById('chess-status').textContent='Temps écoulé';Babi.vibrate(160);chess.state.turn='b';chess.selected=null;chessRender();scheduleChessAI('timeout')}},1000)}
  function finishChess(title,text,won,emoji){chess.gameOver=true;clearInterval(chess.timer);clearTimeout(chess.aiTimer);if(won){chess.best=Babi.setBest('chess',chess.score);document.getElementById('chess-highscore').textContent=chess.best}Babi.win('chess',title,text,emoji)}
  function scheduleChessAI(reason='move'){clearInterval(chess.timer);document.getElementById('chess-status').textContent='IA en réflexion…';chess.state.turn='b';chess.aiTimer=setTimeout(()=>playChessAI(reason),LEVELS[chess.level].aiDelay)}
  function makeChessHuman(m){clearInterval(chess.timer);const p=chess.state.board[m.from],captured=m.enPassant?'p':chess.state.board[m.to];const before=p.type;chess.state=chessApply(chess.state,m);chess.selected=null;updateScore(chess,10);if(captured)updateScore(chess,PIECE_VALUES[captured.type]===320||PIECE_VALUES[captured.type]===330?40:Math.round(PIECE_VALUES[captured.type]/3));if(before==='p'&&chess.state.board[m.to].type==='q')updateScore(chess,80);if(findKing(chess.state,'b')>=0&&isSquareAttacked(chess.state,findKing(chess.state,'b'),'w'))updateScore(chess,35);chessRender();const end=chessEndCheck(chess.state,'b');if(end==='checkmate'){updateScore(chess,500);finishChess('ÉCHEC ET MAT !',`Victoire • Score ${chess.score}` ,true,'♛');return}if(end==='stalemate'){finishChess('PAT',`Partie nulle • Score ${chess.score}`,false,'🤝');return}scheduleChessAI('move')}
  function playChessAI(){if(chess.gameOver)return;const m=bestChessMove(chess.state,LEVELS[chess.level].chessDepth);if(!m){const end=chessEndCheck(chess.state,'b');if(end==='checkmate'){finishChess('ÉCHEC ET MAT',`L’IA gagne • Score ${chess.score}`,false,'🤖');return}finishChess('PAT',`Partie nulle • Score ${chess.score}`,false,'🤝');return}const from=m.from,to=m.to;chess.state=chessApply(chess.state,m);const piece=document.querySelector(`#chess-board .square:nth-child(${from+1}) .piece`);if(piece){piece.classList.add('ai-moving')}setTimeout(()=>{chessRender();const end=chessEndCheck(chess.state,'w');if(end==='checkmate'){finishChess('ÉCHEC ET MAT',`L’IA gagne • Score ${chess.score}`,false,'🤖');return}if(end==='stalemate'){finishChess('PAT',`Partie nulle • Score ${chess.score}`,false,'🤝');return}chess.state.turn='w';document.getElementById('chess-status').textContent='À votre tour';chessHumanTimer()},180)}
  function initChess(){clearInterval(chess.timer);clearTimeout(chess.aiTimer);chess.state=initialChess();chess.selected=null;chess.gameOver=false;resetChessScore();document.getElementById('chess-status').textContent=`${LEVELS[chess.level].label} • À votre tour`;chessRender();chessHumanTimer()}

  // ---------------- DAMES (dames volantes + prises multiples) ----------------
  function initialCheckers(){const b=Array(64).fill(null);for(let r=0;r<3;r++)for(let c=0;c<8;c++)if((r+c)%2===1)b[idx(r,c)]={color:'b',king:false};for(let r=5;r<8;r++)for(let c=0;c<8;c++)if((r+c)%2===1)b[idx(r,c)]={color:'r',king:false};return {board:b,turn:'r'}}
  function cloneCheckers(s){return {board:s.board.map(p=>p?{...p}:null),turn:s.turn}}
  function checkersCaptureSteps(s,from,color){const p=s.board[from];if(!p)return[];const [r,c]=rc(from),out=[];if(p.king){for(const [dr,dc] of DIR4){let rr=r+dr,cc=c+dc,enemy=-1;while(inside(rr,cc)){const v=s.board[idx(rr,cc)];if(!v){if(enemy>=0)out.push({from,to:idx(rr,cc),capture:enemy});rr+=dr;cc+=dc;continue}if(v.color===color||enemy>=0)break;enemy=idx(rr,cc);rr+=dr;cc+=dc}}}else{for(const [dr,dc] of DIR4){const mr=r+dr,mc=c+dc,tr=r+2*dr,tc=c+2*dc;if(!inside(tr,tc)||!inside(mr,mc))continue;const mid=s.board[idx(mr,mc)];if(mid&&mid.color!==color&&!s.board[idx(tr,tc)])out.push({from,to:idx(tr,tc),capture:idx(mr,mc)})}}return out}
  function checkersSimpleMoves(s,from,color){const p=s.board[from],out=[];if(!p)return out;const [r,c]=rc(from);if(p.king){for(const [dr,dc] of DIR4){for(let n=1;n<8;n++){const rr=r+dr*n,cc=c+dc*n;if(!inside(rr,cc))break;const t=s.board[idx(rr,cc)];if(t)break;out.push({from,to:idx(rr,cc)})}}}else{const d=color==='r'?-1:1;for(const dc of [-1,1]){const rr=r+d,cc=c+dc;if(inside(rr,cc)&&!s.board[idx(rr,cc)])out.push({from,to:idx(rr,cc)})}}return out}
  function applyCheckerStep(s,m){const n=cloneCheckers(s),p={...n.board[m.from]};n.board[m.from]=null;n.board[m.to]=p;if(m.capture!==undefined)n.board[m.capture]=null;const [r]=rc(m.to);if(!p.king&&((p.color==='r'&&r===0)||(p.color==='b'&&r===7)))p.king=true; n.board[m.to]=p;return n}
  function allCheckersMoves(s,color=s.turn){const captures=[];for(let i=0;i<64;i++)if(s.board[i]?.color===color)captures.push(...checkersCaptureSteps(s,i,color).map(m=>({...m,sequence:[m]})));if(captures.length)return captures.map(m=>m.sequence?m:{...m,sequence:[m]});const moves=[];for(let i=0;i<64;i++)if(s.board[i]?.color===color)moves.push(...checkersSimpleMoves(s,i,color).map(m=>({sequence:[m]})));return moves}
  function expandCaptureSequences(s,from,color){const results=[];const first=checkersCaptureSteps(s,from,color);if(!first.length)return[];function dfs(state,current,seq){const next=checkersCaptureSteps(state,current,color);if(!next.length){results.push(seq);return}for(const m of next){const n=applyCheckerStep(state,m);dfs(n,m.to,[...seq,m])}}for(const m of first){const n=applyCheckerStep(s,m);dfs(n,m.to,[m])}return results}
  function allTurnCheckersSequences(s,color=s.turn){let captureSeq=[];for(let i=0;i<64;i++)if(s.board[i]?.color===color)captureSeq.push(...expandCaptureSequences(s,i,color));if(captureSeq.length)return captureSeq;return allCheckersMoves(s,color).map(x=>x.sequence)}
  function checkersEval(s){let v=0;for(const p of s.board)if(p)v+=(p.color==='b'?1:-1)*(p.king?175:100);const bm=allTurnCheckersSequences(s,'b').length,rm=allTurnCheckersSequences(s,'r').length;v+=(bm-rm)*7;return v}
  function checkersSearch(s,depth,alpha=-Infinity,beta=Infinity){const moves=allTurnCheckersSequences(s,s.turn);if(!moves.length)return s.turn==='b'?-500000:500000;if(depth===0)return checkersEval(s);const max=s.turn==='b';let best=max?-Infinity:Infinity;for(const seq of moves){let n=cloneCheckers(s);for(const m of seq)n=applyCheckerStep(n,m);n.turn=max?'r':'b';const val=checkersSearch(n,depth-1,alpha,beta);if(max){best=Math.max(best,val);alpha=Math.max(alpha,best)}else{best=Math.min(best,val);beta=Math.min(beta,best)}if(beta<=alpha)break}return best}
  function bestCheckersSequence(s,depth){const moves=allTurnCheckersSequences(s,'b');if(!moves.length)return null;if(depth===1)return moves[Math.floor(Math.random()*moves.length)];let best=-Infinity,choice=moves[0];for(const seq of moves){let n=cloneCheckers(s);for(const m of seq)n=applyCheckerStep(n,m);n.turn='r';const v=checkersSearch(n,depth-1,-Infinity,Infinity);if(v>best){best=v;choice=seq}}return choice}
  function legalHumanCheckersFrom(from){const all=allTurnCheckersSequences(checkers.state,'r');const filtered=all.filter(seq=>seq[0].from===from);return filtered.length?filtered:[]}
  function checkersRender(){const board=document.getElementById('checkers-board');board.innerHTML='';const options=checkers.selected!==null?legalHumanCheckersFrom(checkers.selected):[];const targets=new Map();options.forEach(seq=>targets.set(seq[0].to,seq[0].capture!==undefined));for(let i=0;i<64;i++){const sq=document.createElement('button');const [r,c]=rc(i);sq.className=`square ${(r+c)%2?'dark':'light'}`;if((r+c)%2===0)sq.disabled=true;if(i===checkers.selected)sq.classList.add('selected');if(targets.has(i))sq.classList.add(targets.get(i)?'capture':'legal');const p=checkers.state.board[i];if(p){const disk=document.createElement('span');disk.className=`checker-piece ${p.color==='r'?'red':'black'} ${p.king?'king':''}`;sq.appendChild(disk)}sq.addEventListener('click',()=>checkersClick(i));board.appendChild(sq)}}
  function checkersClick(i){if(checkers.gameOver||checkers.state.turn!=='r')return;const p=checkers.state.board[i];if(checkers.selected===null){if(p?.color==='r'){const choices=legalHumanCheckersFrom(i);if(choices.length){checkers.selected=i;checkersRender();Babi.vibrate(18)}else Babi.toast('Cette pièce n’a aucun coup légal')}}else{if(p?.color==='r'){checkers.selected=i;checkersRender();return}const seq=legalHumanCheckersFrom(checkers.selected).find(x=>x[0].to===i);if(!seq){Babi.toast('Coup illégal');return}makeCheckersHuman(seq[0])}}
  function checkersHumanTimer(){clearInterval(checkers.timer);checkers.timeLeft=LEVELS[checkers.level].seconds;document.getElementById('checkers-timer').textContent=checkers.timeLeft;checkers.timer=setInterval(()=>{if(checkers.gameOver||checkers.state.turn!=='r'){clearInterval(checkers.timer);return}checkers.timeLeft--;document.getElementById('checkers-timer').textContent=checkers.timeLeft;if(checkers.timeLeft<=0){clearInterval(checkers.timer);checkers.state.turn='b';checkers.selected=null;checkers.mustContinue=null;checkersRender();document.getElementById('checkers-status').textContent='Temps écoulé';Babi.vibrate(160);scheduleCheckersAI(true)}},1000)}
  function finishCheckers(title,text,won,emoji){checkers.gameOver=true;checkers.mustContinue=null;clearInterval(checkers.timer);clearTimeout(checkers.aiTimer);if(won){checkers.best=Babi.setBest('checkers',checkers.score);document.getElementById('checkers-highscore').textContent=checkers.best}Babi.win('checkers',title,text,emoji)}
  function startCheckersAI(){clearInterval(checkers.timer);document.getElementById('checkers-status').textContent='IA en réflexion…';checkers.state.turn='b';checkers.aiTimer=setTimeout(playCheckersAI,LEVELS[checkers.level].aiDelay)}
  function scheduleCheckersAI(){startCheckersAI()}
  function makeCheckersHuman(step){clearInterval(checkers.timer);const wasKing=!!checkers.state.board[step.from]?.king;checkers.state=applyCheckerStep(checkers.state,step);checkersRender();updateScore(checkers,10);if(step.capture!==undefined)updateScore(checkers,100);const moved=checkers.state.board[step.to];if(!wasKing&&moved?.king)updateScore(checkers,60);checkers.selected=step.to;const opponent='b';const opponentMoves=allTurnCheckersSequences(checkers.state,opponent);if(!opponentMoves.length){updateScore(checkers,500);finishCheckers('DAMIER DOMINÉ !',`Victoire • Score ${checkers.score}`,true,'👑');return}const moreCaptures=checkersCaptureSteps(checkers.state,step.to,'r');if(step.capture!==undefined&&moreCaptures.length){checkers.mustContinue=step.to;checkers.status='Rafle continue';document.getElementById('checkers-status').textContent='Rafle continue — à vous';checkersRender();checkersHumanTimer();return}checkers.selected=null;checkers.mustContinue=null;checkers.state.turn='b';checkersRender();scheduleCheckersAI()}
  function checkersWasKingBefore(step){const s=checkers.state;return s.board[step.to]?.king&&((s.board[step.to].color==='r'&&rc(step.to)[0]===0)||(s.board[step.to].color==='b'&&rc(step.to)[0]===7))}
  function playCheckersAI(){if(checkers.gameOver)return;const seq=bestCheckersSequence(checkers.state,LEVELS[checkers.level].checkersDepth);if(!seq){finishCheckers('VOUS AVEZ GAGNÉ !',`Victoire • Score ${checkers.score}`,true,'🏆');return}let stepIndex=0;const doStep=()=>{if(checkers.gameOver||stepIndex>=seq.length){checkers.state.turn='r';checkers.selected=null;document.getElementById('checkers-status').textContent='À votre tour';checkersRender();checkersHumanTimer();return}const step=seq[stepIndex++];checkers.state=applyCheckerStep(checkers.state,step);checkersRender();const t=document.querySelector(`#checkers-board .square:nth-child(${step.to+1}) .checker-piece`);t?.classList.add('ai-moving');if(stepIndex<seq.length)setTimeout(doStep,230);else{const endMoves=allTurnCheckersSequences(checkers.state,'r');if(!endMoves.length){finishCheckers('PARTIE TERMINÉE',`L’IA gagne • Score ${checkers.score}`,false,'🤖');return}setTimeout(doStep,180)}};doStep()}
  function resetCheckersScore(){checkers.score=0;document.getElementById('checkers-score').textContent='0';document.getElementById('checkers-highscore').textContent=checkers.best}
  function initCheckers(){clearInterval(checkers.timer);clearTimeout(checkers.aiTimer);checkers.state=initialCheckers();checkers.selected=null;checkers.mustContinue=null;checkers.gameOver=false;resetCheckersScore();document.getElementById('checkers-status').textContent=`${LEVELS[checkers.level].label} • À votre tour`;checkersRender();checkersHumanTimer()}

  document.addEventListener('start-chess',initChess);document.addEventListener('stop-chess',()=>{clearInterval(chess.timer);clearTimeout(chess.aiTimer);chess.gameOver=true});document.addEventListener('start-checkers',initCheckers);document.addEventListener('stop-checkers',()=>{clearInterval(checkers.timer);clearTimeout(checkers.aiTimer);checkers.gameOver=true});
  document.addEventListener('set-level-chess',e=>{if(LEVELS[e.detail.level]){chess.level=e.detail.level;initChess()}});document.addEventListener('set-level-checkers',e=>{if(LEVELS[e.detail.level]){checkers.level=e.detail.level;initCheckers()}});
  document.getElementById('chess-reset').addEventListener('click',initChess);document.getElementById('checkers-reset').addEventListener('click',initCheckers);
})();
